# Generated by Django 5.0.3 on 2024-06-23 11:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="consent",
            new_name="notification_option",
        ),
    ]
